# Generated by Django 3.2.6 on 2021-09-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210911_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='start_date',
        ),
    ]
